// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/02/2025, 12:27:25
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/composables/**/*.{js,ts,mjs}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/utils/**/*.{js,ts,mjs}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/a.hay.MA/Documents/Code Projects/Folder-Strucutre/Folder-Strucutre/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;